### ISSUE TITLE
How to write back to the OFX file

### ISSUE THREAD

**Issue by rodrigoprimo** [csingley/ofxtools#10]
I wonder if there is a way to write back to the OFX file (or to create a new OFX file) after parsing and modifying it with ofxtools?

Thanks!

**Comment by csingley** [comment]
I currently have no plans to implement OFX generation, which functionality I don't need.

This package is just intended to support a core subset of OFX client functionality.

**Comment by rodrigoprimo** [comment]
Thanks for your response @csingley. I might need this functionality in the future. If I decide to implement it (I will first check if there are other softwares that support this), is this something you would be interested in seeing being added to ofxtools?

**Comment by csingley** [comment]
Sure, I'm willing to consider it - more open source OFX software is a good thing.  But it would require a pretty substantial rewrite... the current design of the parser and the type classes presupposes a one-way flow.  I baked in a lot of assumptions in order to efficiently support both OFXv1 and OFXv2 with no dependencies outside stdlib.  Ripping that stuff out and redoing it would be a chore; you'd need a good reason.

An alternative would be to help out [libOFX](http://libofx.sourceforge.net/).  If I were a real programmer instead of a finance person, I probably would have made Python bindings to libOFX instead of writing this package (although it was fun to do).  The author of libOFX is actually looking to add OFX generation code, so if you can program in C, you'd probably get a lot more bang for the buck in that way.  Lots of people use libOFX; very few people use ofxtools.

I'm happy to leave the discussion open - it's just not work that I personally am interested in doing.

**Comment by csingley** [comment]
[reopening]

**Comment by csingley** [comment]
You may be pleased that I found a simple way to implement the functionality you were asking for; it's in [5986c7d](https://github.com/csingley/ofxtools/commit/5986c7d6533c8c5dcfa8bbd27a869992cf539aa8).

To regenerate an OFX file:
```
parser = OFXTree()
parser.parse('/path/to/ofx/file')
ofx = parser.convert()
elem = ofx.to_etree()
import xml.etree.ElementTree as ET
ET.tostring(elem)
```
This is still new & untested as of just yet.  Feel free to play around with it in the meantime though.

**Comment by csingley** [comment]
This is done in [f5f726b](https://github.com/csingley/ofxtools/commit/f5f726bc7f474ea67726ec6f173c461e17b4dff1)

**Comment by rodrigoprimo** [comment]
Thanks!
