### ISSUE TITLE
Incorrect regex for type SECURITY in ofx header

### ISSUE THREAD

**Issue by ksoftirqd** [csingley/ofxtools#11]
The regex for SECURITY type in ofx 1.x needs to be fixed:
https://github.com/csingley/ofxtools/blob/master/ofxtools/header.py#L19

according to the specification, values for SECURITY can be NONE or TYPE1 and it fails to recognize header with:

> ofxtools.header.OFXHeaderError: Can't recognize OFX Header

when value is TYPE1

**Comment by csingley** [comment]
This is fixed in [3356fec](https://github.com/csingley/ofxtools/commit/3356fec072e7dccaf17158f0c6cfe62e0d27d67d) along with some much-needed refactoring of the old and nasty code in that module.  Proper unit tests for the OFX headers have also been checked in.

Thanks for reporting the bug, let me know if you find any more.
