### ISSUE TITLE
crash on convert due to comment length

### ISSUE THREAD

**Issue by gde82** [csingley/ofxtools#12]
Using ofxtree, trying to convert an ofx file using tree.convert() (like given in the readme as an example).
I get an error because of a comment being too long  `ValueError: Can't create STMTTRN.name: '<lengthy comment>i' is too long; max length=32`.

error seems to raise from ofxtools/models.py

**Comment by csingley** [comment]
That's the OFX specification

http://www.ofx.net/downloads/OFX%202.2.pdf

Section 11.4, page 214

**Comment by gde82** [comment]
Agreed, the source should be corrected before using ofxtree. 
But shouldn't convert() truncate and raise a warning in those cases rather than simply crash ?

**Comment by csingley** [comment]
The ofxtools parser could indeed use better error handling.  What would be needed would be the model signaling to the parser whether a violation on any particular field is a deal-breaker or not.

I'd be worried about truncating fields as a matter of policy, because sometimes FIs violate the length restrictions on fields that matter (like investment ticker symbols).

If you look through ofxtools/models.py (search for "relax") you'll see several instances where I changed the spec for exactly this reason... FIs violate the spec because Quicken doesn't enforce it, it's just a string that's too long, and these days everybody has GB of memory, so who really cares?

If it's just STMTTRN.name I don't mind changing it in the source... if you search models.py for "relax" you'll see a few instances where I've already done this, and STMTTRN.name is exactly the kind of field you know FIs are going to abuse.

I'd encourage you to patch your own copy of models.py for the time being - change STMTTRN.name from String(32) to String(255) (line 386) and see if anything else blows up.  Do me a favor and let me know which fields we're having a problem with.

Thanks for reporting!

**Comment by csingley** [comment]
As a start, [b30fce2](https://github.com/csingley/ofxtools/commit/b30fce261b497c4ff33a046869143062a627b99a) introduces a NagString type that issues a warning instead of crashing.  Based on your issue, I've used it for PAYEE.name, which seems like a likely candidate.
