### ISSUE TITLE
License needs clarification

### ISSUE THREAD

**Issue by kcattakcaz** [csingley/ofxtools#126]
Hi, I noticed that the LICENSE file states this project is available under the GPL v3: https://github.com/csingley/ofxtools/blob/master/LICENSE

However, in PyPI it indicates the project is available under the MIT License.  Probably they are getting it from here: https://github.com/csingley/ofxtools/blob/master/setup.py#L52

I assume* currently the LICENSE file is authoritative and the project is GPL v3?  That may be a surprise for some users that only looked at the PyPI page and didn't double-check that file, and they may be failing to meet their obligations under that license (or even know that their programs are subject to them).

Could you clarify your intent and update either or both files to make them consistent?  

If GPL v3 is your intent, it's probably* a pretty straightforward fix to correct PyPI, though a heads-up to those that depend on this may be prudent.

If MIT is your intent, well I'm not really sure, but it appears* as the copyright holder you have options around relicensing new versions to MIT, making old versions available under a dual-license, etc: https://www.gnu.org/licenses/gpl-faq.html#HeardOtherLicense

*I'm not a lawyer 🤷‍♂️

**Comment by csingley** [comment]
Thanks for bringing this to my attention.

A perusal of the `git log` suggests that the `LICENSE` file has always (since 2010!) contained the text of the GPL v3, while the `setup.py` (added in 2015) has always claimed an MIT license.

For the record, my intention has always been the first-claimed license; `ofxtools` is licensed for use by others under the terms of version 3 of the GNU Public License, by the beard of Stallman!  I don't think it matters much, as anybody attempting to monetize my work here will presumably be doing so in the form of some web service.... but I do feel an aversion to anybody actually selling software that incorporates this library, absent my consent.

I'll fix up the `setup.py` accordingly, which will propagate to PyPI.

You are the first person to notice this discrepancy in the 6 years it's obtained.  I think you win some sort of prize.  Does this actually matter to you??

**Comment by csingley** [comment]
OK, should be showing GPLv3 here.

https://pypi.org/project/ofxtools/

Thanks for reporting!
