### ISSUE TITLE
Multiple clientuids required

### ISSUE THREAD

**Issue by redstreet** [csingley/ofxtools#127]
[Chase requires a fixed clientuid](https://ofxtools.readthedocs.io/en/latest/client.html?highlight=clientuid#setting-clientuid) which #22 adds support for. However, I don't see a way to maintain multiple client uids for chase, if logging in with multiple, separate accounts.

One approach would be to allow `--clientuid` to optionally use a specified clientuid. This would be particularly helpful to scripts that don't want to depend on ofxtools' config, but rather, be able to specify a clientuid via the command line invocation. Happy to submit a PR, but would like to find out what you think of this first?

**Comment by csingley** [comment]
Sure, that's better than what we're doing now... plus backward compatibility can be maintained by passing `nargs="?"` and keeping the existing behavior by default if not overwritten.

But, y'know, if you're scripting, I don't know why you'd want to use `ofxget` instead of just writing your own little front end to call `ofxtools.Client.request_statement()`.  There's no need to run all that ugly code for parsing ugly CLI args.

**Comment by redstreet** [comment]
Agreed, frontend calling the library is ideal. It does come in very handy though to test/develop, and also to be able to share command line invocations :).

I'll send the PR in a minute.
