### ISSUE TITLE
Regression using 'hasattr' on STMTRS

### ISSUE THREAD

**Issue by PhracturedBlue** [csingley/ofxtools#137]
As of version 0.8.20 this worked, but it stopped working in 0.8.21

```import datetime
from ofxtools.models import *

stmt = STMTRS(
    curdef='USD',
    bankacctfrom=BANKACCTFROM(bankid="bank", acctid="12345678", accttype='CHECKING'),
    banktranlist=BANKTRANLIST(dtstart=datetime.datetime.now().astimezone(), dtend=datetime.datetime.now().astimezone()),
    ledgerbal=LEDGERBAL(balamt=1000, dtasof=datetime.datetime.now().astimezone()),
    ballist=BALLIST())
hasattr(stmt, 'invposlist')
```
Throws:
```
Traceback (most recent call last):
  File "t1.py", line 10, in <module>
    hasattr(stmt, 'invposlist')
  File ".venv/lib/python3.9/site-packages/ofxtools/models/base.py", line 519, in __getattr__
    return getattr(subagg, attr)
  File ".venv/lib/python3.9/site-packages/ofxtools/models/base.py", line 517, in __getattr__
    subagg = getattr(self, subaggregate)
  File ".venv/lib/python3.9/site-packages/ofxtools/Types.py", line 117, in __get__
    return self.data[parent]
KeyError: <BANKTRANLIST dtstart='2021-10-20 09:06:13.141100-07:00' dtend='2021-10-20 09:06:13.141121-07:00' len=0>
```

I do not believe `hasattr` should ever throw an exception (since that is the whole purpose of using it.

**Comment by csingley** [comment]
`hasattr`  basically does this:

```
def hasattr(obj, attrname):
    try:
        getattr(obj, attrname)
        return True
    except AttributeError:
        return False
```

However you're getting a KeyError instead, which it doesn't handle.

This is clearly an implementation flaw in the descriptor protocol for `Types.SubAggregate` and/or `models.base.Aggregate`.

I think you're just running into problems because `Aggregate` offers proxy access to attributes of its `SubAggregates`, so that e.g. you can just refer to `stmt.accttype` instead of saying `stmt.bankacctfrom.accttype`.

This is indeed a bug that I'll fix... but whatever it is you're doing, may I suggest that you instead avail yourself of `isinstance` and friends?  The `ofxtools` library is well-suited to type dispatch.  You're not really subclassing the models and types that implement the OFX specification, are you?
