### ISSUE TITLE
OFXTree lacks fromstring() method

### ISSUE THREAD

**Issue by coderforlife** [csingley/ofxtools#161]
OFXTree lacks fromstring() method which ElementTree has. That method would be useful when using OFXClient responses which are strings and then sent directly to OFXTree.

The workaround isn't too bad: `parser.parse(io.BytesIO(byte_string))`

But still, surprising that that method was missing.

**Comment by csingley** [comment]
> OFXClient responses which are strings

They are?? I remember going to some trouble to package them all in `BytesIO`; which ones did I miss?

To be clear, the `ElementTree` class does not have an instance method `fromstring()` (which is why `OFXTree` didn't inherit one); `fromstring` is an alias for the `XML` function in the module namespace.

But I mean, sure, if you want `fromstring()`, I'm not really opposed, have at it.   It should be pretty simple to implement with `ofxtools.header.parse_header()` and `ofxtools.Parser.TreeBuilder.feed()`, just follow along with the implementation in `ofxtools.Parser.OFXTree`.

**Comment by coderforlife** [comment]
I was mistaken, a `BytesIO` is returned making this kind of a moot point.
