### ISSUE TITLE
models too strict ?

### ISSUE THREAD

**Issue by rienafairefr** [csingley/ofxtools#2]
I have ofx files that fail to pass the tree.convert() pass:

In the file, the field BANKACCTFROM/BANKID is more than 9 chars, and also the field LEDGERBAL/BALAMT is "None" instead of "0", which causes unrecoverable types conversion errors. Is it the ofx file that is outside standard ofx specs or is it ofxtools that is too strict ?
Cheers,

**Comment by csingley** [comment]
What version of OFX is claimed in the OFX header?

You can download various versions of the spec from here:
http://ofx.net/DownloadPage/Downloads.aspx

BANKID is specified as 9 chars by the specs I'm using.  BALAMT is specified as a numerical amount.

FIs serve up a huge amount of noncompliant and terribly formatted OFX, with each company having its own quirks.  I've made ofxtools pretty strictly standard-compliant by design, and I'd like to keep the core parser code clean.  It might be a good idea to add hooks to preprocess OFX or handle exceptions; a library of FI quirks could maybe be assembled and shipped with the package.  This could conceivably handle quirks like writing "None" instead of "0" for amounts.

The BANKID... huh.  It wouldn't necessarily bother me to relax the length constraints on BANKID/ACCTID (or allow these length constraints to be specified at instantiation)... but I'd like to understand what's going on with your data.  What country is your bank in?  What is the format of the BANKID they're pushing out?

Thanks for the bug report.

**Comment by rienafairefr** [comment]
I think it's claimed to be OFX 1.02 (VERSION:102 in the header)

This is an ofx outputted by a website not really a FI, and they put winancial.com in BANKID a bit longer than 9 chars :-) 

You're right you should keep ofxtools clean of quirks and stick to the specs. I'll look around in the code if I can help. Closing the issue as far as I'm concerned. Thanks
