### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by PierreRochard** [csingley/ofxtools#21]
Hi Chris! I noticed SQLAlchemy no longer is part of this project. Is there a roadmap for separating it out into a separate module or ofxtools going in a different direction?

Thanks,

Pierre

**Comment by csingley** [comment]
I got rid of ofxalchemy mostly because that SQL schema isn't useful; I haven't really been able to use it in applications.  It is better to define the ORM schema as part of the application (tailoring it to the needs of the project) and feed in data from the pure Python ofxtools.Parser.

For this reason, I didn't imagine anyone was actually using ofxalchemy as written.  If you are, though, I wouldn't want to leave you high & dry... let me know what your needs are and I'll see what I can do for you.  It's certainly great to use SQLAlchemy with OFX.

**Comment by PierreRochard** [comment]
I am using it. I see your point though. What I had been doing was similar - just at the database level. I have an "ofx" schema that is the raw data, and has views (aka saved queries) joining relevant tables that I use in the application. I also have a separate "accounting" schema that has double entry journal entries, with links to the relevant "cash" entry in the ofx schema.

To be clear you're not leaving me high & dry as I have a fork: https://github.com/pierrerochard/ofxtools . I fix minor bugs I experience but it's otherwise not a big deal.

**Comment by csingley** [comment]
The backdrop here is that I'm making some significant changes to the structure of ofxtools.models to make everything much easier to understand and maintain... the recent release was about half of it, and I'll be ready to push the other half pretty soon.

Once that's done it should be easy to add back ofxalchemy; I'm happy to put it in if you want it.

ofxalchemy is probably fairly useful is all you're doing is pulling out STMTTRN and LEDGERBAL data.  I mostly use the INVSTMT data, and the ofxalchemy schema doesn't work well for that.

If you find some bugs feel free to kick them upstream.  OFX servers are extremely diverse in their implementation of the spec, and I'm always interested in the challenges of parsing real world data.

**Comment by PierreRochard** [comment]
That sounds good to me. I've only done a little with the investment data (https://github.com/PierreRochard/pacioli/blob/master/pacioli/database/sql_views.py#L174-L216)

The issues  have been in the area of Client connectivity with Chase, for example they had added a clientuid field that needed to be present in the request: https://github.com/PierreRochard/ofxtools/commit/58757eac90669fc969466e1f70c3d4ed88b82879

**Comment by csingley** [comment]
I haven't touched the core Client code since they added CLIENTUID to the spec.  I'll implement CLIENTUID when I get some time... what are you using for CLIENTUID values?  I assume they want these to be persistent between connections.

I think that pacioli link is to a private repository.  Off & on I'm doing some work on double entry accounting... so far I haven't seen any open-source Python ledger programs that will work very well with importing investment data.

Thanks for the kind words.  I've gotten a lot of use out of open source software over the years; I'm pleased to make a small contribution of my own.  I'm glad you find it useful.

**Comment by csingley** [comment]
OK Pierre, I re-added ofxalchemy in [2c2a360](https://github.com/csingley/ofxtools/commit/2c2a36070d035cb53bb6a1954eb0ea40129de6cd).  Let me know if that works for you.

**Comment by PierreRochard** [comment]
Wow that was fast! I'll try it out this weekend. (re: pacioli, oops, it's public now if you want to take a peek!)

**Comment by csingley** [comment]
@PierreRochard are you still using ``ofxtools.ofxalchemy``?  I've been putting in work on the library, and again I find myself with the urge to to remove code I'm not willing to maintain.  I have created some documentation with suggestions on how to use ``ofxtools`` with ``sqlalchemy`` more sensibly (i.e. close to how I do it).
