### ISSUE TITLE
INVACCTFROM model order

### ISSUE THREAD

**Issue by scottbdr** [csingley/ofxtools#31]
In investment.py, I had to put brokerid before acctid to get a valid request when using for Fidelity. That appears to be correct order per OFX spec.

class INVACCTFROM(Aggregate):
    """ OFX section 13.6.1 """
    acctid = String(22, required=True)
    brokerid = String(22, required=True)

change to:

class INVACCTFROM(Aggregate):
    """ OFX section 13.6.1 """
    brokerid = String(22, required=True)
    acctid = String(22, required=True)

**Comment by csingley** [comment]
Right you are!  Thank you for reporting

**Comment by csingley** [comment]
Fixed by [4e14c9f](https://github.com/csingley/ofxtools/commit/4e14c9f54d60f8dd4ae529172473d4271a060f3c).

Sorry for the delay; submitting a pull request is appreciated.

**Comment by scottbdr** [comment]
Thanks! will do next time... I'm just getting start with actually using GitHub.

**Comment by scottbdr** [comment]
On the subject of Fidelity... I've been getting responses back with headers like this:
<?xml version="1.0" encoding="UTF-8" standalone="no"?><?OFX OFXHEADER="200" VERSION="220" SECURITY="NONE" OLDFILEUID="NONE" NEWFILEUID="701c7a4d-84e9-44c6-85a7-204121d6f359"?<OFX><SIGNONMSGSRSV1><SONRS>

Notice the missing closing ">"...  Wondering what the best approach is for dealing with that - right now I've modified the v2  header regexp adding a question mark on that character to get things working. Any thoughts?

**Comment by scottbdr** [comment]
Sorry... here is the XML for the above comment: `<?xml version="1.0" encoding="UTF-8" standalone="no"?><?OFX OFXHEADER="200" VERSION="220" SECURITY="NONE" OLDFILEUID="NONE" NEWFILEUID="701c7a4d-84e9-44c6-85a7-204121d6f359"?<OFX><SIGNONMSGSRSV1><SONRS>`

**Comment by csingley** [comment]
Huh, that's pretty messed up, and kind of a pain in the ass to work around.

Sadly I don't have a Fidelity login to verify the malformation.  But if they're really breaking the OFX spec, I'd recommend at least trying to submit a bug report to Fido... I'd guess that's their own code, not an off-the-shelf server.

We don't really need much of any information from the OFXHEADER... but if you follow the logic in Parser.OFXTree.parse(), we do need the CHARSET out of the header for OFXv1 in order to decode the OFX payload properly (which fixes some annoying i18n issues for European users of ofxtools).   So you can't just comment out the lines in OFXHeader.parse() after the various readline() calls have advanced the source to the beginning of the OFX payload (which would be my first tactic).

But monkey-patching the OFXHeaderV2 regex is fairly ugly, and will annoy you if you're working with multiple FIs.  Might be your best bet though, ugh.

I'm loathe to introduce too many contortions into library code just to work around one FI who can't follow the simplest basics of a published spec... but I'm open to suggestions.

IMO it's worth the time getting up to speed on git workflow.  It's pretty great, even if your skills are as poor as mine.

**Comment by scottbdr** [comment]
Yup, that's pretty much what I thought... just was wondering if you had some other ideas. I agree changing the library code for Fidelity doesn't make sense - if I have some time maybe I'll try to chase them down to fix it. Thanks for the help - git skills are coming along :)
