### ISSUE TITLE
SIGNONMSG ordering

### ISSUE THREAD

**Issue by boehms** [csingley/ofxtools#32]
It looks like there is a ordering problem with the signal message.

```
client = OFXClient('https://ofx.chase.com', org='B1', fid='10898', version=103)
response = client.request_profile(dryrun=True)
print(response.read())
```

gives the following:
```
OFXHEADER:100
DATA:OFXSGML
VERSION:103
SECURITY:NONE
ENCODING:USASCII
CHARSET:NONE
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:005c89b8-96b0-41ad-9935-5d036d98b187

<OFX>
  <PROFMSGSRQV1>
    <PROFTRNRQ>
      <PROFRQ>
        <CLIENTROUTING>NONE</CLIENTROUTING>
        <DTPROFUP>19900101050000</DTPROFUP>
     </PROFRQ>
     <TRNUID>0b52de61-d4b6-4167-8160-9c4808ca1afb</TRNUID>
    </PROFTRNRQ>
  </PROFMSGSRQV1>
  <SIGNONMSGSRQV1>
    <SONRQ>
      <APPVER>2300</APPVER>
      <DTCLIENT>20180329173946</DTCLIENT>
      <FI>
        <ORG>B1</ORG>
        <FID>10898</FID>
      </FI>
      <USERPASS>anonymous00000000000000000000000</USERPASS>
      <LANGUAGE>ENG</LANGUAGE>
      <USERID>anonymous00000000000000000000000</USERID>
      <APPID>QWIN</APPID>
    </SONRQ>
  </SIGNONMSGSRQV1>
</OFX>
```

SIGNONMSGSRQV1 should be the first message set according to the spec.

**Comment by csingley** [comment]
What version of Python are you using?

**Comment by boehms** [comment]
2.7

**Comment by csingley** [comment]
<sigh> I thought I'd dealt firmly with the whole Py2K-doesn't-remember-class-definition-order situation.  Apparently not.  I'll dig back through the relevant methods of Types.Element and base.Aggregate and see what issue remains.

This probably won't help you, but none of this is a concern under Py3K, which stores class attributes in OrderedDict instances.

**Comment by boehms** [comment]
I can confirm that the ordering is correct with python 3.6.

I do seem to have another problem though. It looks like the OFX is not correct if OFX version is 103.

**Comment by csingley** [comment]
Yeah I'll update that too.

**Comment by csingley** [comment]
VERSION: 103 is validated correctly as of [0bbf62d](https://github.com/csingley/ofxtools/commit/0bbf62dd7e37d8b56e67aa762f5fecc12381f2b5).

**Comment by csingley** [comment]
...and I believe your Py2k ordering problem should be fixed by [86dfdc7](https://github.com/csingley/ofxtools/commit/86dfdc7092282a832684df48cb957aaf1b25e75c).  It works for me; do me the favor of testing it to see if it works for you.

Your issue actually exposes what I'd consider a more fundamental structural defect in ofxtools that isn't addressed by the above quick commit... that is, OFX.sonrqmsgsv1 and OFX.profrqmsgsv1 are created on OFX instances as Aggregates, not SubAggregates... which is why it wasn't immediately obvious they weren't already inheriting InstanceCounterMixin.

Not exactly in accord with the principle of least surprise, and worth restructuring to be less hacky.   Needless to say that work will take a bit more time and consideration to do right.  Thank you for reporting.

**Comment by rianhunter** [comment]
Additionally after reviewing the code, I believe it is already correct and @boehms must be running an older version of ofxtools.

**Comment by csingley** [comment]
I verified the misbehavior under Py2.7, and that the patch I submitted fixed it.

The problem was with Aggregate.__init__().  If you instantiate models.ofx.OFX(signonmsgsrqv1=models.signon.SIGNONMSGRSQV1(**some_kwargs), profmsgsrqv1=models.profile.PROFMSGSRQV1(**more_kwargs)).... OFX.__init__() takes the dict keys from OFX.spec(), and pops the corresponding values from kwargs passed in to OFX.__init__().  These are what get set as attributes on the newly-initialized OFX instance... and they're instances of Aggregate subclasses (**not** SubAggregate subclasses) and hence didn't inherit InstanceCounterMixin.

So I just changed Aggregate to inherit InstanceCounterMixin, and it works fine.  _counter is read by Aggregate._ordered_attrs().

But this is more confusing than it needs to be. Looking at the model class, it sure looks like SIGNONMSGSRQV1 et al. are SubAggregates that inherit from Element and hence InstanceCounterMixin.  But that's only true of the class itself, not class instances.

**Comment by csingley** [comment]
Just to be clear, this is a different codepath than is used by the parser.  The parser uses Aggregate.from_etree() as a constructor, whereas the client writes OFX using Aggregate.__init__().

**Comment by rianhunter** [comment]
Not to belabor the point, and I trust you on this but it still seems like `_counter` is only ever queried on objects of the class object (in `_ordered_attrs`). The objects being set in `Aggregate.init()` (themselves being instances of Aggregate) are never set on `cls.__dict__`, instead they are set on `self`. Are you 100% sure that your verification on Python 2.7 isn't a random fluke?

**Comment by csingley** [comment]
By all means, please do belabor... after all, it is your code.
Yeah you're right, I see it.  Let me roll back and repeat my tests sometime when I'm not trying to work and also smoking crack.  One or the other, but not both.

**Comment by csingley** [comment]
@rianhunter - [ad441b1](https://github.com/csingley/ofxtools/commit/12f43958da96c866d77ee494ad7b5db700e1f52d) adds the `prettyprint` kwarg to OFXClient.download().  Do me a favor and see if that satisfies Vanguard.

**Comment by boehms** [comment]
I installed it using pip. It is 0.5

**Comment by rianhunter** [comment]
@boehms Yup, 0.5 was affected by this bug. If you install version 0.5.1 from pip you should be in the clear. Closing
