### ISSUE TITLE
Unable to parse due to date/time format?

### ISSUE THREAD

**Issue by cbrum11** [csingley/ofxtools#48]
Thanks for creating this great tool.  I'm running the following command and getting the below issue...

![image](https://user-images.githubusercontent.com/20428729/47612713-0de1b480-da4e-11e8-83f1-d1cc2cd07979.png)

![image](https://user-images.githubusercontent.com/20428729/47612694-91e76c80-da4d-11e8-8acc-b05bfe5f7015.png)

Any thoughts?

**Comment by csingley** [comment]
Hmm.  Is it the `ofxget` command throwing that error?  Are you running a current version of `ofxtools`?  Can you give me the complete error trace being thrown?

See:
1) You're looking at a parse error; the parser isn't stripping the end tag off the data.  However, the `ofxget` command doesn't need to parse <DTCLIENT>.
2) Not only is `OFXAdapter` not in the current codebase, I don't recall ever having written such a class.  I mean, the whole library is OFX-specific; what would it be adapting?  To what?
3) That doesn't look like an error message I would write - "atomic field"?

If `ofxtools.Parser` is blowing up on something so basic, I definitely want to track that down... but it looks like you're using someone else's parser, and it's throwing an error.

`

**Comment by cbrum11** [comment]
Thanks for the response.  I'm a python novice, so all help is appreciated.  I'm not intending to use any other parser.  I'm just trying to walk through this tutorial.  One thing to note, I was not able to get the command `python setup.py install --user` to run.  Thanks again for your help.

https://pypi.org/project/ofxtools/

Yes, it's the ofxget command that's throwing the error.  Full error/command below.

![image](https://user-images.githubusercontent.com/20428729/47619647-51b8d600-daaf-11e8-844a-b00e1ac6e77b.png)

My ofxtools version below...
![image](https://user-images.githubusercontent.com/20428729/47619652-61d0b580-daaf-11e8-8d6f-15f0cc53020a.png)

**Comment by csingley** [comment]
Apologies for deleting your previous msg; the screenshot was leaking account info you probably didn't want up here.

It may be that what you're seeing is error output from USAA's server... `OFXRequest.OFXRequest.SignOnMsgsRqUn.SignOnMsgsRqV1.SonRq.DtClient` doesn't correspond to the data structures we have in `ofxtools`.  This would probably be a message from USAA's OFX parser that they haven't handled correctly... it looks like they're not raising an HTTP error, instead just dumping a Java error trace directly into an HTTP response with OK status.

That is to say, the last code being run is line#300 in `ofxtools.Client`, rather than line#304 (which would raise an error pointing to the line# inside `ofxtools` that is failing).  You could quickly confirm this by inserting a statement right before line#300 of `ofxtools.Client`, something like this:
`print('No HTTP error here!')`
If you insert that statement, run your `ofxget` command again, and see that text printed in the output... then it's not an error being raised by `ofxtools`.

If that's what's going on, USAA appears to be telling you that for OFXv1 they won't accept closing tags on leaf elements... it blew up on DTCLIENT, which is the first non-aggregate the parser encountered.

Try appending `--unclosedelements` to your `ofxget` command line; it might solve the problem.

**Comment by cbrum11** [comment]
So a few updates.  When I went add the print statement around line 300 in Client.py I noticed it looked different than the current version on github.  

Specifically it was missing, 'from ofxtools.models import ACCTINFORQ, ACCTINFOTRNRQ, SIGNUPMSGSRQV1'

Instead of seeing if anything else was missing I uninstalled ofxtools and everything associated with it.  I then manually downloaded/unzipped the current master, updated the config file, updated the Client.py file with your suggested print statement, and ran the command line with and without '--unclosedelements'.

Not using '--unclosedelements' gives the same error as before.  Using '--unclosedelements' now gives the response '<OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>2000<SEVERITY>ERROR<MESSAGE>Were sorry, an error has occurred during processing.  Please try again.'  Along with some additional text that contains comprimising info and another code, 15500.

Thanks again for all your help.

**Comment by cbrum11** [comment]
Additionally I noticed in the response is the following...

`<FID>24592</FI>`

However the USAA FID should be **24591** and this is what I've set it as in the config and FI file?

**Comment by csingley** [comment]
Best to use master; it's hardly in heavy development right now.

Yeah, these are server error messages, not from `ofxtools`.  You cleared their low-level parser error, then ran into something else downline they didn't like.

Can you confirm that the 2000 error also printed out the text you inserted?

So about all I can tell you is to append a `--dryrun` arg to your `ofxget` command.  That will print out the <STMTRQ> being generated without posting it to the server.  Visual inspection should confirm conformance to the OFX spec.  On the off chance you're not intimately familiar with the OFX spec, you can post it here... username/pw should automatically be sanitized by `--dryrun`, but you'll want to overwrite `<ACCTID>` as I mentioned.

However, this is really not going to solve your problem.  We've already seen that USAA breaks compliance with the OFX spec by not allowing end tags... this is because they coded to Quicken compliance, not OFX compliance (Quicken doesn't use closing tags for OFXv1).  Now the question is, where the hell else are they out of compliance?  Their error message is uninformative.

Try updating `<FID>` to what they say it is.  Worth a shot.

**Comment by cbrum11** [comment]
Incremental success scouring the interwebs.  
https://github.com/euforic/banking.js/issues/33#issuecomment-265277833

Instead of my username, using my padded account number and padded USAA member number gives...
`<OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>15500<SEVERITY>ERROR<MESSAGE>Some or all of the information you have entered is invalid. Please call toll free (1-800-531-6347) for assistance.</STATUS>`

**Comment by csingley** [comment]
Well, you've hurdled parser errors and dodged validation errors; the server is deigning to speak OFX to you, and you're down to authentication errors.  That's improvement.

Try calling USAA customer service or rooting around their website.  Ask them how to set up Quicken access to your account (i.e. what they want you to put in for these fields).  Putting the same thing into `ofxtools` is likely to work, I imagine.

**Comment by cbrum11** [comment]
SUCCESS!!!  I found an obscure forum that discussed using **_the USAA PIN when prompted for the password, not the actual password used for login_**.  This worked perfectly!

For anyone else running into this issue, the USAA command that worked for me is as follows...

NOTE:  

1. -u (username) should be your USAA account number NOT your USAA login username. It should also be 9 numbers long.  If it is not 9 numbers long, add 0's to the beginning of the number until it is.

2. -C (checking account) should be 10 numbers long.  If it is not 10 numbers long, add 0's to the beginning fo the number until it is.

3. -d is just an example... I didn't experiment with other dates.

`>ofxget -u 012345678 --bankid 314074269 -C 0123456789 -d 20180901 --fid 24591 --org USAA --version 102 --unclosedelements https://service2.usaa.com/ofx/`

Thanks again for all your help @csingley.  What an adventure this has been haha.

**Comment by csingley** [comment]
Hopefully your obscure forum was [this one](http://www.ofxhome.com/ofxforum/viewtopic.php?id=47536):

> for anyone else trying to get usaa to work, ive recently had success with the following

>username is your usaa id number, found in the website
>password is your regular pin number that the website asks you for so often

>account number needs to be 10 digits, so 0 pad it

http://ofxhome.com is pretty much the go-to resource for this kind of thing.

713 represent, since the days when there was a porno movie theater in the Rice Village.  Happy to meet up with people who use my code; my email's in the source.  If you get down Montrose ways https://www.blacksmithhouston.com/ is the place.

**Comment by bdube** [comment]
The comments in this issue helped me with USAA too. One note, I think the URL should be `https://service2.usaa.com/ofx/OFXServlet` (that is, the `/OFXServlet` is missing in a comment above).

Online search results seem to suggest that expecting USAA to upgrade to a later version of OFX is a waste of time. But if you run the junk from USAA through [fixofx](https://github.com/henriquebastos/fixofx) you can get OFX/200 XML. My apologies if ofxtools can also do that and I overlooked it.

Thank you for ofxtools.

**Comment by csingley** [comment]
> Online search results seem to suggest that expecting USAA to upgrade to a later version of OFX is a waste of time

As long as Intuit supports OFXv1, there will be FIs that see no point in upgrading.  It's not really needed if you don't want to support advanced features like bill pay through OFX, etc.

> But if you run the junk from USAA through fixofx you can get OFX/200 XML. My apologies if ofxtools can also do that and I overlooked it.

Thanks for the reference to `fixofx`; I hadn't been aware of the project.

`ofxtools` should support any version of the OFX spec.  It's easy to get it to parse OFXv1 and dump back to OFXv2, I just haven't knocked up a script that does so since I haven't perceived a use case.  I guess it might be handy for users of some financial software that can't handle OFXv1.

> Thank you for ofxtools.

You're most welcome.  Free software is great.

**Comment by ps23Rick** [comment]
I hate to re-open this but I'm having a similar issue with USAA.. ugg.. and can't quite figure it out.  Based on the output I think it wants to do a robot check or something.. 

```
% ofxget stmt --url https://service2.usaa.com/ofx/OFXServlet -u <myUSAAnumber> --bankid 314074269 -C <myaccount-num> --fid 24591 --org USAA --version 102 --unclosedelements usaa
Password:
Traceback (most recent call last):
  File "/System/Volumes/Data/Users/rickf/Library/Python/3.8/bin/ofxget", line 8, in <module>
    sys.exit(main())
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/scripts/ofxget.py", line 1612, in main
    REQUEST_HANDLERS[args["request"]](args)
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/scripts/ofxget.py", line 723, in request_stmt
    with client.request_statements(
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/Client.py", line 354, in request_statements
    RqCls2url = self._get_service_urls(
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/Client.py", line 434, in _get_service_urls
    profile = self.request_profile(
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/Client.py", line 521, in request_profile
    parser.parse(response)
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/Parser.py", line 82, in parse
    self.header, message = self._read(source)
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/Parser.py", line 115, in _read
    header, message = parse_header(source)
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/header.py", line 294, in parse_header
    header, header_end_index = OFXHeaderV1.parse(rawheader)
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/header.py", line 81, in parse
    raise OFXHeaderError(f"OFX header is malformed:\n{rawheader}")
ofxtools.header.OFXHeaderError: OFX header is malformed:
<html>


<head>
	<meta name="ROBOTS" content="nofollow,noindex">
	<title>

	        System Error
	      | USAA</title>
	<style media="screen" type="text/css">
```

I tried using different versions of the OFX stuff (v 1.02, 1.51, 2.0, 2.02) and they all had issues but the 2.x are different -- as indicated below :

```
[Traceback (most recent call last):
  File "/System/Volumes/Data/Users/rickf/Library/Python/3.8/bin/ofxget", line 8, in <module>
    sys.exit(main())
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/scripts/ofxget.py", line 1612, in main
    REQUEST_HANDLERS[args["request"]](args)
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/scripts/ofxget.py", line 722, in request_stmt
    client = init_client(args)
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/scripts/ofxget.py", line 558, in init_client
    client = OFXClient(
  File "/Users/rickf/Library/Python/3.8/lib/python/site-packages/ofxtools/Client.py", line 295, in __init__
    raise ValueError(f"OFX version {self.version} must close all tags")
ValueError: OFX version 202 must close all tags](url)

```

I feel like I'm sooooo close but not quite there yet.. Any thoughts/suggestions would be awesome!!!  Thanks!

**Comment by bdube** [comment]
Hi @ps23Rick 

I think USAA's OFX servlet is having a moment. I see the same system error response.

**Comment by ps23Rick** [comment]
Hmm.. that begs the question though.. I use MoneyWiz (I'm transitioning away from it) and it's OFX stuff works just fine as of a few minutes ago.. I wonder what this code is doing that USAA doesn't specifically want to see -- but that apparently the code used by MW must do things different enough that it's ok.

Maybe I'll have to play around with it a little more if it's still barfing tomorrow.  Thank you!

**Comment by csingley** [comment]
Do me a favor.  Don’t necropost on closed bug tickets because you’re experiencing an unrelated error.
