### ISSUE TITLE
OFX version 1.6 causes OFXHeaderError

### ISSUE THREAD

**Issue by chbndrhnns** [csingley/ofxtools#49]
My online banking tool upgraded its OFX export to 1.6 according to the release notes. Since then, I am receiving the following error when trying to parse an exported file.

Error
```
ofxtools.header.OFXHeaderError: OFX header is malformed: OFXHEADER:100

DATA:OFXSGML
VERSION:160
SECURITY:NONE
ENCODING:UTF-8
CHARSET:NONE
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE
```

Here is a sanitized example file (renamed to txt):
[MoneyMoney-o7LV7S.txt](https://github.com/csingley/ofxtools/files/2567411/MoneyMoney-o7LV7S.txt)

**Comment by csingley** [comment]
It's actually the ENCODING field... the header regex was written wrong, and only accepted alpha characters in that position.  This is actually the first time I've seen OFX version 1 using UTF-8 encoding.

This is fixed in [f7cf08c](https://github.com/csingley/ofxtools/commit/f7cf08ca88224e9ae8bba608c556fea7de387abd)

Thanks for the bug report; sorry for the delay in fixing it.
