### ISSUE TITLE
`datetime` object returned should not be naive

### ISSUE THREAD

**Issue by turicas** [csingley/ofxtools#6]
I have something like this in my OFX file: `<DTSERVER>20150804111745[-3:GMT]`. When parsing it using `ofxtools` I get a naive `datetime.datetime` object:

``` python
>>> from ofxtools import OFXTree
>>> tree = OFXTree()
>>> tree.parse('test.ofx')
>>> converted = tree.convert()
>>> converted.sonrs.dtserver
datetime.datetime(2015, 8, 4, 14, 17, 45)
```

The returned object is correct (`2015-08-04 11:17:45 GMT-3` is `2015-08-04 14:17:45 UTC`) but it lost the timezone information after conversion.

I think the object returned should be something like this:

``` python
import pytz  # pip install pytz

offset = '-3'  # take it from OFX
timezone = pytz.FixedOffset(int(offset) * 60)
object_returned = datetime.datetime(2015, 8, 4, 11, 17, 45, tzinfo=timezone)
```

**Comment by csingley** [comment]
Yeah I dodged the issue by just using GMT for everything; my understanding of Python timezone handling is not very good.  I am aware of the issue, but have not come to any conclusions regarding its importance.

Can you explain why it matters what timezone the OFX server is in?

**Comment by turicas** [comment]
The transaction data may be generated in different timezones so it would be useful to know which one.
Anyway, I think explicit is better than implicit and the library should expose the **real** value to the user instead of omitting some data that is inside the file.

**Comment by csingley** [comment]
I'm trying to understand the use case here - why would it be useful to know in what TZ a transaction occurred?

Right now the base ofxtools has no dependencies beyond Python standard library, and I'd prefer to keep it that way.  I'm also not in a hurry to clutter ofxalchemy's DB schema and attribute access to implement, absent a good reason to do so.

What's an example of what TZ awareness gets us?

**Comment by turicas** [comment]
Hmmm... thinking again: maybe there are no good use cases for this. It's just metadata.

**Comment by euresti** [comment]
Actually, this is a bit of an issue because the data in is assumed to be local time but the data coming out is converted to UTC.  This means I can't easily turn around and send back data I get from the server back to the server.  My suggestion (and I can make a PR if you like) is to return the datetime objects with a tzinfo of UTC.  And on the input side if you see a tzinfo use it to adjust the time to UTC before sending it to the server.  Let me know if you want this.

**Comment by turicas** [comment]
@euresti you're right! I've reopenned the issue. :)

**Comment by csingley** [comment]
Not keeping correct time when round-tripping to a server is indeed a bug that should be corrected.

I'll state plainly that I have negligible comprehension of / experience with TZ issues.  That being said this looks like a solid improvement - particularly the addition of utils.UTC, which is exactly what I haven't known how to do.

Could I prevail upon you to add a unit test or two to tests.test_types.DateTimeTestCase demonstrating that the patch performs correctly - particularly DateTime.unconvert(), which doesn't really cover this at present?  Looks like the patch does finally address the FIXME about local time though!

Thanks.

**Comment by euresti** [comment]
I noticed 2 issues with the tests.

1. tests.test_types.DateTimeTestCase.test_unconvert is localtime dependent.  It always fails for me because I'm in Pacific time.
2. All I can really test is passing in `utils.UTC`.  I don't know how I would test `pytz` support.

Would it be possible to add `pytz` as a dependency?

**Comment by csingley** [comment]
The test case needed is along these lines:
```
In [1]: import datetime

In [2]: import ofxtools

In [3]: converter = ofxtools.Types.DateTime()

In [4]: def roundtrip(dt_foreign):
   ...:     return converter.unconvert(converter.convert(dt_foreign))
   ...: 
   ...: 

In [5]: def tripround(dt_python):
   ...:     return converter.convert(converter.unconvert(dt_python))
   ...: 
   ...: 

In [6]: roundtrip('20180601010000')
Out[6]: '20180601010000'

In [7]: tripround(datetime.datetime(2018,6,1,1))
Out[7]: datetime.datetime(2018, 5, 31, 17, 0, tzinfo=<UTC>)
```
The problem here is that `Types.DateTime.unconvert()` assumes TZ-naive `datetime`s are local time; it actually needs to default to UTC.  This would at least be a consistent representation of my starting posture towards timezones, i.e. an OFX library has little business handling them, and should just use UTC internally.

TZ data enters the library either from OFX server responses, or client applications handing in Python datatypes.  Well-formed OFX responses are trivial to timezone correct; they always specify GMT offset unambiguously per the spec.  It's true that incoming Python datatypes do need to deal with TZ headaches, but surely that responsibility can and should be delegated to the application that's dealing with user input, DB persistence, foreign code, or what have you.

It might be better to have a stricter API, and require that input to `Types.DateTime.unconvert()` be a TZ-aware `datetime` instance (rather than accepting naive `datetime`s and also `date` instances, as at present).  That'd be much clearer.

I'm reluctant to add dependencies to `ofxtools.`  What would importing `pytz` really buy us?  Honest question.

AFAICT, having `pytz` available would offer two potential benefits:
1. It would help `Types.DateTime.convert()` work around buggy OFX server implementations (e.g. pre-2014 Interactive Brokers OFX downloads, which left the GMT offset blank but included TZ name) ... but this is frankly pretty low priority; and
2. It would make `Client.py` more robust.  The use of local time for user input is somewhat problematic; it would really be better to use the TZ of the OFX server, which could be included in the config file.  This is where you need a TZ library like `pytz`.

Anything else?

**Comment by csingley** [comment]
> It might be better to have a stricter API, and require that input to Types.DateTime.unconvert() be a TZ-aware datetime instance (rather than accepting naive datetimes and also date instances, as at present). That'd be much clearer.

I've committed this change as [6ff1665](https://github.com/csingley/ofxtools/commit/6ff16653ce140e2ecc478508fc745dfd4cd9e5aa)
