### ISSUE TITLE
Crash on stmt request (JP Morgan)

### ISSUE THREAD

**Issue by Zburatorul** [csingley/ofxtools#64]
The following command produces a crash with no modifications to ofxget.cfg:
`ofxget stmt jpmorgan -u some_name --all`
I'm attaching the exception trace in a file. [ofxget-error1.log](https://github.com/csingley/ofxtools/files/3522048/ofxget-error1.log)

Note that removing the "--all" and supplying it with an account number (-C 12345) does not produce a crash.
`ofxget stmt jpmorgan -u somename -C 12345 --bankid 071000013`
 Response also attached. [ofxget-no-error1.log](https://github.com/csingley/ofxtools/files/3522047/ofxget-no-error1.log)

Python 3.7.2, ofxtools 0.8.20

**Comment by csingley** [comment]
Thanks for the report.  There are a few problems here.

The most basic one is that the `jpmorgan` server seems to be completely broken.  You are sending it requests for `ACCTINFO` and `STMT`, but it is always responding with an OFX profile... notice that it never actually sends you your account #s or your transaction data at all, despite indicating a successful signon.  This is a total break from the OFX spec, not to mention being completely useless.

Try using the `chase` server instead; I use that successfully.  However, you will need to jump through a couple hoops to set up access, as documented [here](https://ofxtools.readthedocs.io/en/latest/client.html#setting-clientuid).

Moving beyond that... passing the `--write` or `--all` options to `ofxget` ask it to parse the returned OFX response to extract information.  Needless to say, this is a more complicated operation that executes much more code, with many more opportunities to trigger bugs.  I'll fix bugs, and am helped by bug reports... but if you're interested in getting your hands on your OFX data, consider avoiding `--write` and `--all`.  To be pragmatic, just enter your settings into `ofxget.cfg` and skip all that logic if it's not working for you.

Finally... by trying to parse the PROFRS, you've managed to expose two separate bugs in the library.

1)  As indicated by the error traceback you posted, Chase is giving you a sequence of `<INVALIDACCTTYPE>` elements.  I incorrectly specified that as a single data element in the data model for the banking message set.  That's trivial to fix.

2) Fixing that exposes an error in the Aggregate instance constructor methods... it's only set up to handle sequences of Aggregates, not Elements.  I believe I know how to fix that, but it's a bit more involved.

Thanks for reporting, I appreciate it.  However, you shouldn't need to wait for me to fix my bugs to get use out of the library.  Let me know if you get it it working.

**Comment by Zburatorul** [comment]
Everything you say makes a lot of sense. I wasn't sure whether jpmorgan is the right server to use for Chase bank accounts rather than CCs. In my opi
I followed the steps in your link one more time, and this time I understood that the code Chase generates on their website is not an AUTH token and should be ignored.
I too can now obtain account info and transactions.

This is going off-topic, but do you have any advice on how to get GnuCash/AqBanking to submit correct OFX requests like ofxget does.

**Comment by Zburatorul** [comment]
I have a different error to report for the same command combination. I'll add it here.
`ofxget stmt citi -u username --all`
(nothing in .cfg file)
Error log attached.
[error2.log](https://github.com/csingley/ofxtools/files/3522571/error2.log)

Finally, if instead
`ofxget stmt citi -u <correct username> --creditcard <correct credit card number with no spaces>`
Then, upon entering the correct OR incorrect password, the output is the same. 
[noerror2.log](https://github.com/csingley/ofxtools/files/3522586/noerror2.log)

I tried passing it version 220 and appver 2700, but same response.

**Comment by csingley** [comment]
At least you're able to get data.  Once you've got Chase set up, I think you should be able to configure GnuCash with the same parameters you used in ofxtools (especially the same CLIENTUID) and have it work.  If not, try asking their user mailing list; they're a pretty solid group.

You're getting OFX profile responses from `citi`, same as `jpmorgan` above.  Both of these responses are coming from CheckFree servers.  My guess is that these are dead links - this is what CheckFree returns instead of HTTP error 404 for former customers who quit paying.

> Is there a way to ask ofxget to output the messages it sends, not just receives?

Sure, you just append the `--dryrun` option ( `-n` for short).  I did this for `jpmorgan` to confirm that I was sending them ACCTINFORQ but they were sending me PROFRS instead of ACCTINFORS.

**Comment by Zburatorul** [comment]
@csingley, What is the right avenue for questions about how ofxget interacts with specific institutions? I don't think they are bugs per se, at least not on the part of ofxget, and it seems excessive to open a new one for each new question.

**Comment by csingley** [comment]
@Zburatorul, good question.

This Github repository does have an associated wiki (currently empty) that perhaps could be put to some use.  It's not a great way to ask me questions, though.  No notifications.

If you're hacking on ofxtools code, my email address is in the source.

I think you'll find that many questions are ultimately about the OFX protocol itself, and its (extremely messy) implementation by various financial institutions.  Essentially, we're trying to reverse-engineer Quicken.

The [OFX spec](https://www.ofx.net/downloads.html) is a bit of a beast, but it's worth scanning at least a little of it at a high level in order to know how the protocol operates.

When I looked at the SGML output you posted above, my thought process went like this: "I sent an ACCTINFORQ, so they should be sending me an ACCTINFORS.  That string doesn't even appear in the response at all.  So what the hell did they send me?  It should be there right below the signon response block (SONRS), which reports no error.  Wait, what's that instead?  PROFRS?  A profile response??  But I didn't send a !*@& profile request!  What fresh hell is this?"

You don't have to read very deeply into the OFX spec to achieve that level of understanding.

But the good news is that CheckFree's bizarre behavior exercised the ofxtools code in unexpected ways, thereby uncovering some bugs - one of them fairly important.  Thanks for reporting.

**Comment by Zburatorul** [comment]
No longer an issue.
