### ISSUE TITLE
V1 Header uses CR as newline, causing parse_header to fetch more than it should

### ISSUE THREAD

**Issue by mvbentes** [csingley/ofxtools#83]
After some debugging I noticed my bank ends lines with CR on the header and with LF on the data.
`open` default `newline` for `rb` is LF, so right from the start it will fetch the whole header and the <OFX> tag here:

    while True:
        # OFX header is read by nice clean machines, not meatbags -
        # should not contain 💩, 漢字, or what have you.
        line = source.readline().decode("ascii")
        if line.strip():
            break

I saw that for V2 you rewind the file:

        source.seek(0)
        decoded_source = source.read().decode(OFXHeaderV2.codec)
        header, header_end_index = OFXHeaderV2.parse(decoded_source)
        message = decoded_source[header_end_index:]

And thought that would work here to, as the `header_end_index` had the correct position. I do not know if there were other reasons not to do it for V1 also.

I do not know if fixing this is within the scope of the library, but seems simple enough. Without this fix I get an `IndexError: pop from empty stack` because it tries to close some tag that was not opened, since it got consumed with the header.

Thanks for all the hard work. Let me know if some information is missing.

Image showing the offending part of the file, the debugging session on the above snippet and the value of `line` on the first run of the while loop.
![image](https://user-images.githubusercontent.com/11647983/85648197-9e82f480-b676-11ea-8c99-3a341f79f20c.png)

**Comment by csingley** [comment]
> After some debugging I noticed my bank ends lines with CR on the header and with LF on the data.

I'd thought the FIs had long since exhausted my capacity for surprise, but always there is some some novel torture sprung from their foreheads like a diabolical Athena.  They don't even have consistent newlines within the same HTTP response?!

On general principles, I suggest you file a bug report with your bank, but you know that will bear no fruit.

Old versions of the OFXv1 spec (e.g. v1.0.3) are silent on the matter of newline representation... Section 1.2.1 is the relevant part of the spec.  By the time OFXv1.6 was published, the working group had seen fit to opine:

> A brief note here that a “blank line” means a carriage return and a linefeed pair – CRLF.

However, since Quicken only implements v1.0.3, nobody reads this spec... and apparently Quicken parses mixed newlines (or else your bank wouldn't send it), so I suppose we'd better, too.

\</whine\>

> I saw that for V2 you rewind the file [...] And thought that would work here to, as the header_end_index had the correct position. I do not know if there were other reasons not to do it for V1 also.

The handling is different between OFXv1 & OFXv2 because OFXv1 declares CHARSET in the header and uses it, whereas OFXv2 (a post-unicode spec) mandates UTF-8 encoding everywhere, thus avoiding this entire class of problems.

However I don't think that difference will cause problems for your proposed solution, since I believe ASCII (the encoding for the OFXv1 header) is a strict subset of UTF-8, CP-1252, and the others.  I think your proposal holds promise!

Have you tried it?  In `header.py`, hange the case where there's no XML header regex match to look something like this:
```
        logger.debug("No XML declaration - OFX version 1")
        rawheader = line + "\n"
        # First line is OFXHEADER; need to read next 8 lines for a fixed
        # total of 9 fields required by OFX v1 spec.
        for n in range(8):
            rawheader += source.readline().decode("ascii")
        header, header_end_index = OFXHeaderV1.parse(rawheader)

        #  Decode the OFX data body according to the encoding declared
        #  in the OFX header
        source.seek(0)
        decoded_source = source.read().decode(header.codec)
        message = decoded_source[header_end_index:]
```

**Comment by mvbentes** [comment]
I ended up doing it like this:

        #  Input source stream position should have advanced to the beginning of
        #  the OFX body tag soup, which is where subsequent calls
        #  to read()/readlines() will pick up. 
        #  The seek call will correct the position when \r newline character is used
        source.seek(header_end_index)
        #  Decode the OFX data body according to the encoding declared
        #  in the OFX header
        message = source.read().decode(header.codec)

And it worked for my files. I also tried it with proper \n newlines on the header and also with some \r\n sprinkled in for good measure and it seemed to run fine on all those cases.

**Comment by csingley** [comment]
Cool, that's fine, thanks.

The right way to do this is to apply the bugfix & verify that the patched code passes the automated tests, i.e. the suite of commands listed in the Makefile for `make test`, which assume you have installed the dependencies given by `pip install -r requirements-development.txt`.

But this is easier for me than for you; I'll take it from here.  Thanks again for hunting this down.

**Comment by csingley** [comment]
Hey there, if you feel like censoring any personal information from your OFX file with the messed-up newlines and sending it to me (either email or just posting it here), I'll write up a test for it & include it in the distribution, trying to make sure that future code tweaks don't break it for you.
